#pragma once
#include "ReportFormatter.h"

// ── HTMLFormatter ──────────────────────────────────────────────────────────
// Renders a self-contained styled HTML report viewable in any browser.
// Use: --format html --output report.html
class HTMLFormatter : public ReportFormatter {
public:
    void format(const Report& report, std::ostream& out) const override {
        writeHead(out);
        writeSummary(out, report);
        writeTable(out, report);
        writeFoot(out);
    }

private:
    static std::string escape(const std::string& s) {
        std::string out;
        for (char c : s) {
            switch (c) {
                case '&': out += "&amp;";  break;
                case '<': out += "&lt;";   break;
                case '>': out += "&gt;";   break;
                case '"': out += "&quot;"; break;
                default:  out += c;
            }
        }
        return out;
    }

    static void writeHead(std::ostream& out) {
        out << R"(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Code Smell Report</title>
<style>
  body  { font-family:'JetBrains Mono',monospace; background:#0b0e13; color:#cdd6f4; padding:32px; }
  h1    { color:#00e5ff; margin-bottom:4px; font-size:28px; }
  .sub  { color:#4a5568; font-size:12px; margin-bottom:32px; }
  .stats{ display:flex; gap:16px; margin-bottom:32px; flex-wrap:wrap; }
  .stat { background:#111520; border:1px solid #1e2535; padding:14px 22px; min-width:110px; }
  .stat .n{ font-size:30px; font-weight:700; }
  .stat .l{ font-size:10px; color:#4a5568; letter-spacing:.1em; text-transform:uppercase; }
  .high  { color:#ff4d6d; } .medium { color:#ffb74d; } .low { color:#a3ff6a; }
  table  { width:100%; border-collapse:collapse; font-size:12px; }
  th     { text-align:left; padding:8px 14px; background:#111520;
           color:#4a5568; font-size:10px; letter-spacing:.12em;
           text-transform:uppercase; border-bottom:1px solid #1e2535; }
  td     { padding:10px 14px; border-bottom:1px solid #1e2535; vertical-align:top; }
  tr:hover td { background:#141824; }
  .badge { display:inline-block; padding:2px 8px; font-size:10px; border-radius:2px; font-weight:600; }
  .HIGH  { background:#ff4d6d22; color:#ff4d6d; border:1px solid #ff4d6d55; }
  .MEDIUM{ background:#ffb74d22; color:#ffb74d; border:1px solid #ffb74d55; }
  .LOW   { background:#a3ff6a22; color:#a3ff6a; border:1px solid #a3ff6a55; }
</style>
</head>
<body>
<h1>Code Smell Report</h1>
)";
    }

    static void writeSummary(std::ostream& out, const Report& report) {
        out << "<p class=\"sub\">Generated by Code Smell Detector &mdash; "
            << report.totalFiles << " file(s) analyzed</p>\n";
        out << "<div class=\"stats\">\n";
        out << "  <div class=\"stat\"><div class=\"n\">"        << report.size() << "</div>"
            << "<div class=\"l\">Total</div></div>\n";
        out << "  <div class=\"stat\"><div class=\"n high\">"   << report.countBySeverity(Severity::HIGH)   << "</div>"
            << "<div class=\"l\">High</div></div>\n";
        out << "  <div class=\"stat\"><div class=\"n medium\">" << report.countBySeverity(Severity::MEDIUM) << "</div>"
            << "<div class=\"l\">Medium</div></div>\n";
        out << "  <div class=\"stat\"><div class=\"n low\">"    << report.countBySeverity(Severity::LOW)    << "</div>"
            << "<div class=\"l\">Low</div></div>\n";
        out << "</div>\n";
    }

    static void writeTable(std::ostream& out, const Report& report) {
        out << "<table>\n<thead><tr>"
            << "<th>Severity</th><th>File</th><th>Line</th>"
            << "<th>Smell</th><th>Message</th>"
            << "</tr></thead>\n<tbody>\n";

        for (auto& v : report.violations) {
            std::string sev = severityToString(v.severity);
            out << "<tr>"
                << "<td><span class=\"badge " << sev << "\">" << sev << "</span></td>"
                << "<td>" << escape(v.filePath)  << "</td>"
                << "<td>" << v.line              << "</td>"
                << "<td>" << escape(v.smellType) << "</td>"
                << "<td>" << escape(v.message)   << "</td>"
                << "</tr>\n";
        }
        out << "</tbody></table>\n";
    }

    static void writeFoot(std::ostream& out) {
        out << "</body>\n</html>\n";
    }
};